name       : python-invoke
version    : 1.7.3
release    : 10
source     :
    - https://github.com/pyinvoke/invoke/archive/refs/tags/1.7.3.tar.gz : a9edaf676284a1dc9a613782d67a4f5dde28629f04cfcfe6dceb267a1643b3a5
homepage   : https://www.pyinvoke.org/
license    : BSD-2-Clause
component  : programming.python
summary    : Pythonic task management & command execution
description: |
    python-invoke is a Python library for managing shell-oriented subprocesses and organizing executable Python code into CLI-invokable tasks.
builddeps  :
    - pkgconfig(python3)
    - python-mock
    - python-pytest-relaxed
    - pyyaml
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 \
        --deselect tests/runners.py \
        --deselect tests/context.py::Context_::sudo::auto_response_merges_with_other_responses
