name       : python-invoke
version    : 1.1.1
release    : 1
source     :
    - https://github.com/pyinvoke/invoke/archive/1.1.1.tar.gz : 772b340244c16db1910ed91c61bc1a817ba87bed66156d99af9ebddc14869e64
license    : BSD-2-Clause
component  : programming.python
summary    : Pythonic task management & command execution
description: |
    python-invoke is a Python (2.7 and 3.4+) library for managing shell-oriented subprocesses and organizing executable Python code into CLI-invokable tasks
builddeps  :
    - python-setuptools
build      : |
    %python3_setup
    %python_setup
install    : |
    %python3_install
    for _f in $installdir/usr/bin/*; do
      mv -v $_f ${_f}3
    done
    %python_install
