name       : python-invoke
version    : 1.4.1
release    : 5
source     :
    - https://github.com/pyinvoke/invoke/archive/1.4.1.tar.gz : ac5880fb5d21f06cc1b29f89736cb8a43b85abea9204b4bb4277458ae025d0b7
license    : BSD-2-Clause
component  : programming.python
summary    : Pythonic task management & command execution
description: |
    python-invoke is a Python library for managing shell-oriented subprocesses and organizing executable Python code into CLI-invokable tasks.
builddeps  :
    - pkgconfig(python3)
    - python-mock
    - python-pytest-relaxed
    - pyyaml
setup      : |
    %patch -p0 < $pkgfiles/invoke-1.4.1-pytest-too-recent.patch
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
