name       : python-invoke
version    : 1.3.0
release    : 2
source     :
    - https://github.com/pyinvoke/invoke/archive/1.3.0.tar.gz : f95915dfbadc0a5526946950160334bf476b282de285af0e7defdb712bb25d8b
license    : BSD-2-Clause
component  : programming.python
summary    : Pythonic task management & command execution
description: |
    python-invoke is a Python (2.7 and 3.4+) library for managing shell-oriented subprocesses and organizing executable Python code into CLI-invokable tasks
builddeps  :
    - python-setuptools
build      : |
    %python3_setup
install    : |
    %python3_install
