name       : python-invoke
version    : 1.6.0
release    : 7
source     :
    - https://github.com/pyinvoke/invoke/archive/refs/tags/1.6.0.tar.gz : b1e49dabbbee8a89b95fd1714f2403cb9bd795f0bb9da0d564fc1213ff02330d
license    : BSD-2-Clause
component  : programming.python
summary    : Pythonic task management & command execution
description: |
    python-invoke is a Python library for managing shell-oriented subprocesses and organizing executable Python code into CLI-invokable tasks.
builddeps  :
    - pkgconfig(python3)
    - python-mock
    - python-pytest-relaxed
    - pyyaml
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    # pytest too old
    rm $workdir/py3build/tests/runners.py
    %python3_test pytest3
