name       : python-invoke
version    : 1.7.1
release    : 9
source     :
    - https://github.com/pyinvoke/invoke/archive/refs/tags/1.7.1.tar.gz : eb9f91616820fe7453f48e5835db4b7258bfa02c8103f21634a3394e07da66f9
homepage   : https://www.pyinvoke.org/
license    : BSD-2-Clause
component  : programming.python
summary    : Pythonic task management & command execution
description: |
    python-invoke is a Python library for managing shell-oriented subprocesses and organizing executable Python code into CLI-invokable tasks.
builddeps  :
    - pkgconfig(python3)
    - python-mock
    - python-pytest-relaxed
    - pyyaml
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 --deselect tests/runners.py
